---
driver:
  name: vagrant
  customize:
    memory: <%= ENV['TEST_KITCHEN_VM_MEMORY'] || 2048 %>
    cpus: <%= ENV['TEST_KITCHEN_VM_CPUS'] || 2 %>

provisioner:
  name: chef_zero
  roles_path: test/fixtures/roles
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "172.16.1.1"}]
    run_list:
      - role[web_and_db]
      - role[web]
    verifier:
      inspec_tests:
        - test/smoke/web_and_db
        - test/smoke/web
  - name: database
    driver:
      network:
        - ["private_network", {ip: "172.16.1.2"}]
    run_list:
      - role[web_and_db]
      - role[database]
    verifier:
      inspec_tests:
        - test/smoke/web_and_db
        - test/smoke/database
